name: Frontend CI/CD

on:
  push:
    branches: [ main ] # Tự động chạy khi push lên main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # B1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # B2: Cài Node.js và dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        run: cd react-movie && npm install

      # B3: Deploy build folder lên server qua SSH
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/*"
          target: "/var/www/your-frontend-folder"
